# Generated by Django 5.2 on 2025-05-24 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_appointmentavailability_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentavailability',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='appointmentavailability',
            unique_together={('doctor', 'start_time')},
        ),
        migrations.AddField(
            model_name='appointmentavailability',
            name='slot_type',
            field=models.CharField(choices=[('short', 'Short (15 minutes)'), ('long', 'Long (30 minutes)')], default='short', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentavailability',
            name='timezone',
            field=models.CharField(default='Australia/Brisbane', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentavailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointmentavailability',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointmentavailability',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='appointmentavailability',
            table=None,
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled_by_patient', 'Cancelled by Patient'), ('cancelled_by_doctor', 'Cancelled by Doctor'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='booked', max_length=30)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('availability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointment.appointmentavailability')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('no_show', 'No Show')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='appointment.appointment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointmentavailability',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointmentavailability',
            name='price',
        ),
    ]
