# Generated by Django 5.2 on 2025-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointmentavailability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled_by_patient', 'Cancelled by Patient'), ('cancelled_by_doctor', 'Cancelled by Doctor'), ('cancelled_by_admin', 'Cancelled by Admin'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='booked', max_length=30),
        ),
    ]
