# Generated by Django 5.2 on 2025-05-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='form',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drug',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='strength',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='repeats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
