# Generated by Django 5.2 on 2025-05-20 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_drug_form_drug_manufacturer_drug_notes_drug_strength_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='is_schedule_8',
            new_name='electronic_chart_eligible',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='molecule',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='notes',
        ),
        migrations.AddField(
            model_name='drug',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='container',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='drug',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='dangerous_drug_fee_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='infusible_indicator',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='max_prescribable_pack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='number_of_repeats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drug',
            name='pbs_code',
            field=models.CharField(default='UNKNOWN', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='program_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='schedule_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
