# Generated by Django 5.2 on 2025-05-22 05:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.CharField(default='UNKNOWN', max_length=10, unique=True)),
                ('drug_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('form', models.CharField(blank=True, max_length=50, null=True)),
                ('strength', models.CharField(blank=True, max_length=50, null=True)),
                ('schedule_code', models.CharField(blank=True, max_length=10, null=True)),
                ('program_code', models.CharField(blank=True, max_length=10, null=True)),
                ('manufacturer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('max_prescribable_pack', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_repeats', models.IntegerField(default=0)),
                ('container', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('dangerous_drug_fee_code', models.CharField(blank=True, max_length=10, null=True)),
                ('electronic_chart_eligible', models.BooleanField(default=False)),
                ('infusible_indicator', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('is_final', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('repeats', models.PositiveIntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_drugs', to='prescriptions.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionSupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('repeats', models.PositiveIntegerField(default=0)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_supplier_products', to='prescriptions.prescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_products.supplierproduct')),
            ],
        ),
    ]
