# Generated by Django 5.2 on 2025-05-27 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prescriptiondrug',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='prescriptionsupplierproduct',
            options={'ordering': ['id']},
        ),
    ]
