# Generated by Django 5.2 on 2025-05-22 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specified', 'Prefer not to say')], max_length=16)),
                ('date_of_birth', models.DateField()),
                ('qualification', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=100)),
                ('medical_registration_number', models.CharField(max_length=50, unique=True)),
                ('registration_expiry', models.DateField(blank=True, null=True)),
                ('prescriber_number', models.CharField(max_length=50, unique=True)),
                ('provider_number', models.CharField(max_length=50, unique=True)),
                ('hpi_i', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('digital_signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specified', 'Prefer not to say')], max_length=16)),
                ('date_of_birth', models.DateField()),
                ('contact_address', models.TextField()),
                ('medicare_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('irn', models.CharField(blank=True, max_length=10, null=True)),
                ('medicare_expiry', models.DateField(blank=True, null=True)),
                ('ihi', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
